// src-tauri/src/badges/definitions.rs

use crate::badges::types::{BadgeDefinition, BadgeRarity, BadgeCategory, BadgeCriteria};

/// Get all badge definitions
pub fn get_all_badge_definitions() -> Vec<BadgeDefinition> {
    vec![
        // ==================== MILESTONE BADGES ====================
        BadgeDefinition {
            id: "first_blood".to_string(),
            name: "First Blood".to_string(),
            description: "Complete your first focus session".to_string(),
            flavor_text: "Every legend starts somewhere.".to_string(),
            icon: "🩸".to_string(),
            rarity: BadgeRarity::Common,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalSessions { count: 1 },
            secret: false,
            share_text: "Just completed my first focus session with Dustoff Reset! The journey begins. 🩸".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FirstBlood".to_string(), "Focus".to_string()],
        },
        BadgeDefinition {
            id: "getting_started".to_string(),
            name: "Getting Started".to_string(),
            description: "Complete 5 sessions".to_string(),
            flavor_text: "You're building a habit.".to_string(),
            icon: "🌱".to_string(),
            rarity: BadgeRarity::Common,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalSessions { count: 5 },
            secret: false,
            share_text: "5 focus sessions down! Building the habit. 🌱 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FocusHabit".to_string()],
        },
        BadgeDefinition {
            id: "double_digits".to_string(),
            name: "Double Digits".to_string(),
            description: "Complete 10 sessions".to_string(),
            flavor_text: "Consistency is showing.".to_string(),
            icon: "🔟".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalSessions { count: 10 },
            secret: false,
            share_text: "10 focus sessions complete! Double digits 🔟 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Consistency".to_string()],
        },
        BadgeDefinition {
            id: "quarter_century".to_string(),
            name: "Quarter Century".to_string(),
            description: "Complete 25 sessions".to_string(),
            flavor_text: "You're not messing around.".to_string(),
            icon: "🎯".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalSessions { count: 25 },
            secret: false,
            share_text: "25 focus sessions! This is becoming who I am. 🎯 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FocusMode".to_string()],
        },
        BadgeDefinition {
            id: "fifty_club".to_string(),
            name: "The Fifty Club".to_string(),
            description: "Complete 50 sessions".to_string(),
            flavor_text: "Elite focus territory.".to_string(),
            icon: "🏅".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalSessions { count: 50 },
            secret: false,
            share_text: "50 sessions. I'm in the Fifty Club now. 🏅 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FiftyClub".to_string()],
        },
        BadgeDefinition {
            id: "centurion".to_string(),
            name: "Centurion".to_string(),
            description: "Complete 100 sessions".to_string(),
            flavor_text: "A hundred battles. A hundred victories.".to_string(),
            icon: "💯".to_string(),
            rarity: BadgeRarity::Epic,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalSessions { count: 100 },
            secret: false,
            share_text: "100 FOCUS SESSIONS. I am the Centurion. 💯 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Centurion".to_string(), "100Sessions".to_string()],
        },
        
        // ==================== STREAK BADGES ====================
        BadgeDefinition {
            id: "three_day_streak".to_string(),
            name: "Trilogy".to_string(),
            description: "3-day focus streak".to_string(),
            flavor_text: "Three days. A pattern emerges.".to_string(),
            icon: "3️⃣".to_string(),
            rarity: BadgeRarity::Common,
            category: BadgeCategory::Streak,
            criteria: BadgeCriteria::DayStreak { days: 3 },
            secret: false,
            share_text: "3-day focus streak! The pattern is forming. 3️⃣ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Streak".to_string()],
        },
        BadgeDefinition {
            id: "week_warrior".to_string(),
            name: "Week Warrior".to_string(),
            description: "7-day focus streak".to_string(),
            flavor_text: "A full week of focus. Respect.".to_string(),
            icon: "📅".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Streak,
            criteria: BadgeCriteria::DayStreak { days: 7 },
            secret: false,
            share_text: "7-DAY FOCUS STREAK! One full week. 📅 #DustoffReset #WeekWarrior".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "WeekWarrior".to_string(), "7DayStreak".to_string()],
        },
        BadgeDefinition {
            id: "fortnight_fighter".to_string(),
            name: "Fortnight Fighter".to_string(),
            description: "14-day focus streak".to_string(),
            flavor_text: "Two weeks of relentless focus.".to_string(),
            icon: "⚔️".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Streak,
            criteria: BadgeCriteria::DayStreak { days: 14 },
            secret: false,
            share_text: "14-DAY STREAK! Two weeks of pure focus. ⚔️ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "14DayStreak".to_string()],
        },
        BadgeDefinition {
            id: "monthly_master".to_string(),
            name: "Monthly Master".to_string(),
            description: "30-day focus streak".to_string(),
            flavor_text: "A month of mastery. You're different now.".to_string(),
            icon: "🗓️".to_string(),
            rarity: BadgeRarity::Epic,
            category: BadgeCategory::Streak,
            criteria: BadgeCriteria::DayStreak { days: 30 },
            secret: false,
            share_text: "30-DAY FOCUS STREAK! A FULL MONTH! I'm not the same person I was. 🗓️ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "MonthlyMaster".to_string(), "30DayStreak".to_string()],
        },
        BadgeDefinition {
            id: "quarterly_quest".to_string(),
            name: "Quarterly Quest".to_string(),
            description: "90-day focus streak".to_string(),
            flavor_text: "Three months. This is your life now.".to_string(),
            icon: "🏆".to_string(),
            rarity: BadgeRarity::Legendary,
            category: BadgeCategory::Streak,
            criteria: BadgeCriteria::DayStreak { days: 90 },
            secret: false,
            share_text: "90-DAY STREAK. THREE MONTHS. This isn't a phase—this is who I am. 🏆 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "90DayStreak".to_string(), "Legendary".to_string()],
        },
        BadgeDefinition {
            id: "yearly_legend".to_string(),
            name: "Yearly Legend".to_string(),
            description: "365-day focus streak".to_string(),
            flavor_text: "One year. Every. Single. Day. You are the legend.".to_string(),
            icon: "👑".to_string(),
            rarity: BadgeRarity::Legendary,
            category: BadgeCategory::Streak,
            criteria: BadgeCriteria::DayStreak { days: 365 },
            secret: false,
            share_text: "365-DAY STREAK. ONE FULL YEAR. Every. Single. Day. 👑 #DustoffReset #YearlyLegend".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "YearlyLegend".to_string(), "365Days".to_string()],
        },
        
        // ==================== PERFORMANCE BADGES ====================
        BadgeDefinition {
            id: "flow_state".to_string(),
            name: "Flow State".to_string(),
            description: "Finish a session with bandwidth ≥ 80".to_string(),
            flavor_text: "You found the zone.".to_string(),
            icon: "⚡".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Performance,
            criteria: BadgeCriteria::MinBandwidth { threshold: 80 },
            secret: false,
            share_text: "Achieved FLOW STATE! Finished with 80+ bandwidth. ⚡ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FlowState".to_string()],
        },
        BadgeDefinition {
            id: "untouchable".to_string(),
            name: "Untouchable".to_string(),
            description: "Finish a session with bandwidth ≥ 90".to_string(),
            flavor_text: "Nothing could break your focus.".to_string(),
            icon: "🛡️".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Performance,
            criteria: BadgeCriteria::MinBandwidth { threshold: 90 },
            secret: false,
            share_text: "UNTOUCHABLE. 90+ bandwidth. Nothing broke my focus. 🛡️ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Untouchable".to_string()],
        },
        BadgeDefinition {
            id: "perfect_session".to_string(),
            name: "Perfect Session".to_string(),
            description: "Finish with 100 bandwidth (no penalties)".to_string(),
            flavor_text: "Flawless. Absolutely flawless.".to_string(),
            icon: "💎".to_string(),
            rarity: BadgeRarity::Epic,
            category: BadgeCategory::Performance,
            criteria: BadgeCriteria::ExactBandwidth { value: 100 },
            secret: false,
            share_text: "PERFECT SESSION. 100 bandwidth. Zero distractions. 💎 #DustoffReset #Perfect".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "PerfectSession".to_string()],
        },
        BadgeDefinition {
            id: "the_wall".to_string(),
            name: "The Wall".to_string(),
            description: "Complete a session with zero distractions".to_string(),
            flavor_text: "They tried. They failed. The wall held.".to_string(),
            icon: "🧱".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Performance,
            criteria: BadgeCriteria::ZeroDistractions,
            secret: false,
            share_text: "THE WALL HELD. Zero distractions. Nothing got through. 🧱 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "TheWall".to_string()],
        },
        BadgeDefinition {
            id: "laser_focus".to_string(),
            name: "Laser Focus".to_string(),
            description: "Return from every delay gate in a session".to_string(),
            flavor_text: "Tempted every time. Resisted every time.".to_string(),
            icon: "🎯".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Performance,
            criteria: BadgeCriteria::PerfectReturns,
            secret: false,
            share_text: "LASER FOCUS. Returned from every temptation. 🎯 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "LaserFocus".to_string()],
        },
        
        // ==================== MODE BADGES ====================
        BadgeDefinition {
            id: "zen_initiate".to_string(),
            name: "Zen Initiate".to_string(),
            description: "Complete 5 Zen mode sessions".to_string(),
            flavor_text: "The training grounds welcome you.".to_string(),
            icon: "🧘".to_string(),
            rarity: BadgeRarity::Common,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::ModeSessions { mode: "Zen".to_string(), count: 5 },
            secret: false,
            share_text: "Zen Initiate. 5 sessions in the training grounds. 🧘 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "ZenMode".to_string()],
        },
        BadgeDefinition {
            id: "flow_rider".to_string(),
            name: "Flow Rider".to_string(),
            description: "Complete 10 Flow mode sessions".to_string(),
            flavor_text: "You ride the wave of focus.".to_string(),
            icon: "🌊".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::ModeSessions { mode: "Flow".to_string(), count: 10 },
            secret: false,
            share_text: "Flow Rider! 10 sessions riding the focus wave. 🌊 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FlowMode".to_string()],
        },
        BadgeDefinition {
            id: "legend_born".to_string(),
            name: "Legend Born".to_string(),
            description: "Complete your first Legend mode session".to_string(),
            flavor_text: "You stepped into the arena.".to_string(),
            icon: "⚔️".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::ModeSessions { mode: "Legend".to_string(), count: 1 },
            secret: false,
            share_text: "LEGEND BORN. I stepped into the arena. ⚔️ #DustoffReset #LegendMode".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "LegendMode".to_string(), "LegendBorn".to_string()],
        },
        BadgeDefinition {
            id: "legend_proven".to_string(),
            name: "Legend Proven".to_string(),
            description: "Complete 10 Legend mode sessions".to_string(),
            flavor_text: "The arena knows your name.".to_string(),
            icon: "🔥".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::ModeSessions { mode: "Legend".to_string(), count: 10 },
            secret: false,
            share_text: "LEGEND PROVEN. 10 sessions in the arena. 🔥 #DustoffReset #LegendMode".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "LegendProven".to_string()],
        },
        BadgeDefinition {
            id: "legend_eternal".to_string(),
            name: "Legend Eternal".to_string(),
            description: "Complete 50 Legend mode sessions".to_string(),
            flavor_text: "Your legend will echo through eternity.".to_string(),
            icon: "👑".to_string(),
            rarity: BadgeRarity::Legendary,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::ModeSessions { mode: "Legend".to_string(), count: 50 },
            secret: false,
            share_text: "LEGEND ETERNAL. 50 sessions in the arena. My legend echoes forever. 👑 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "LegendEternal".to_string()],
        },
        BadgeDefinition {
            id: "extension_survivor".to_string(),
            name: "Extension Survivor".to_string(),
            description: "Survive a +5 minute session extension in Legend mode".to_string(),
            flavor_text: "They extended your suffering. You endured.".to_string(),
            icon: "⏱️".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::SurviveExtensions { count: 1 },
            secret: false,
            share_text: "Session extended +5 min. I SURVIVED. ⏱️ #DustoffReset #LegendMode".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "ExtensionSurvivor".to_string()],
        },
        BadgeDefinition {
            id: "triple_extension".to_string(),
            name: "Triple Extension".to_string(),
            description: "Survive 3+ extensions in a single Legend session".to_string(),
            flavor_text: "15 extra minutes of hell. You're still here.".to_string(),
            icon: "💀".to_string(),
            rarity: BadgeRarity::Epic,
            category: BadgeCategory::Mode,
            criteria: BadgeCriteria::SurviveExtensions { count: 3 },
            secret: false,
            share_text: "3 EXTENSIONS. +15 MINUTES. I SURVIVED THE GAUNTLET. 💀 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "TripleExtension".to_string()],
        },
        
        // ==================== SHAME BADGES (WALKS OF SHAME) ====================
        BadgeDefinition {
            id: "the_fall".to_string(),
            name: "The Fall".to_string(),
            description: "Finish a session with bandwidth ≤ 20".to_string(),
            flavor_text: "You fell. But you didn't quit.".to_string(),
            icon: "📉".to_string(),
            rarity: BadgeRarity::Shame,
            category: BadgeCategory::Shame,
            criteria: BadgeCriteria::MaxBandwidth { threshold: 20 },
            secret: false,
            share_text: "I fell hard today. Bandwidth: 📉 But I didn't quit. #DustoffReset #WalkOfShame".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "WalkOfShame".to_string()],
        },
        BadgeDefinition {
            id: "rock_bottom".to_string(),
            name: "Rock Bottom".to_string(),
            description: "Finish a session with bandwidth ≤ 5".to_string(),
            flavor_text: "You hit the floor. The only way is up.".to_string(),
            icon: "🪨".to_string(),
            rarity: BadgeRarity::Shame,
            category: BadgeCategory::Shame,
            criteria: BadgeCriteria::MaxBandwidth { threshold: 5 },
            secret: false,
            share_text: "ROCK BOTTOM. Bandwidth nearly zero. But I finished. 🪨 #DustoffReset #WalkOfShame".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "RockBottom".to_string(), "WalkOfShame".to_string()],
        },
        BadgeDefinition {
            id: "one_hp".to_string(),
            name: "One HP".to_string(),
            description: "Finish a session with exactly 1 bandwidth".to_string(),
            flavor_text: "Hanging by a thread. Still alive.".to_string(),
            icon: "💔".to_string(),
            rarity: BadgeRarity::Shame,
            category: BadgeCategory::Shame,
            criteria: BadgeCriteria::ExactBandwidth { value: 1 },
            secret: true,
            share_text: "Finished with EXACTLY 1 BANDWIDTH. One HP left. Still standing. 💔 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "OneHP".to_string()],
        },
        BadgeDefinition {
            id: "doomscroller".to_string(),
            name: "Doomscroller".to_string(),
            description: "Get blocked 5+ times in a single session".to_string(),
            flavor_text: "The wall had to work overtime.".to_string(),
            icon: "📱".to_string(),
            rarity: BadgeRarity::Shame,
            category: BadgeCategory::Shame,
            criteria: BadgeCriteria::MinDistractions { count: 5 },
            secret: false,
            share_text: "I tried to escape 5+ times today. The wall said no. 📱 #DustoffReset #Doomscroller".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Doomscroller".to_string()],
        },
        BadgeDefinition {
            id: "serial_offender".to_string(),
            name: "Serial Offender".to_string(),
            description: "Get blocked 10+ times in a single session".to_string(),
            flavor_text: "You really tried everything, huh?".to_string(),
            icon: "🚨".to_string(),
            rarity: BadgeRarity::Shame,
            category: BadgeCategory::Shame,
            criteria: BadgeCriteria::MinDistractions { count: 10 },
            secret: false,
            share_text: "10+ BLOCKS in one session. I'm a serial offender. 🚨 #DustoffReset #WalkOfShame".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "SerialOffender".to_string()],
        },
        BadgeDefinition {
            id: "no_willpower".to_string(),
            name: "No Willpower".to_string(),
            description: "Wait through every delay gate without returning".to_string(),
            flavor_text: "You watched every countdown. Chose distraction every time.".to_string(),
            icon: "🫠".to_string(),
            rarity: BadgeRarity::Shame,
            category: BadgeCategory::Shame,
            criteria: BadgeCriteria::ZeroReturns,
            secret: false,
            share_text: "Zero willpower today. Waited through every gate. 🫠 #DustoffReset #Honest".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "NoWillpower".to_string()],
        },
        
        // ==================== RESILIENCE BADGES ====================
        BadgeDefinition {
            id: "redemption_arc".to_string(),
            name: "Redemption Arc".to_string(),
            description: "Get a Flow State badge after getting The Fall".to_string(),
            flavor_text: "You fell. You rose. You conquered.".to_string(),
            icon: "🔄".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Resilience,
            criteria: BadgeCriteria::Custom { key: "redemption_arc".to_string() },
            secret: true,
            share_text: "THE REDEMPTION ARC IS COMPLETE. I fell. I rose. I conquered. 🔄 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "RedemptionArc".to_string()],
        },
        BadgeDefinition {
            id: "comeback_kid".to_string(),
            name: "Comeback Kid".to_string(),
            description: "Complete a session after breaking a streak".to_string(),
            flavor_text: "The streak died. You didn't.".to_string(),
            icon: "🔙".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Resilience,
            criteria: BadgeCriteria::Custom { key: "comeback_kid".to_string() },
            secret: false,
            share_text: "Broke my streak. Came back anyway. 🔙 #DustoffReset #ComebackKid".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "ComebackKid".to_string()],
        },
        BadgeDefinition {
            id: "phoenix".to_string(),
            name: "Phoenix".to_string(),
            description: "Rebuild a 7+ day streak after losing one".to_string(),
            flavor_text: "From the ashes, you rise.".to_string(),
            icon: "🐦‍🔥".to_string(),
            rarity: BadgeRarity::Epic,
            category: BadgeCategory::Resilience,
            criteria: BadgeCriteria::Custom { key: "phoenix".to_string() },
            secret: true,
            share_text: "Lost my streak. Built a new one. PHOENIX RISING. 🐦‍🔥 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Phoenix".to_string()],
        },
        
        // ==================== TIME BADGES ====================
        BadgeDefinition {
            id: "hour_hero".to_string(),
            name: "Hour Hero".to_string(),
            description: "Accumulate 1 hour of total focus time".to_string(),
            flavor_text: "Your first hour of reclaimed time.".to_string(),
            icon: "⏰".to_string(),
            rarity: BadgeRarity::Common,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalFocusTime { minutes: 60 },
            secret: false,
            share_text: "1 HOUR of focus time with Dustoff Reset! ⏰ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "FocusTime".to_string()],
        },
        BadgeDefinition {
            id: "time_thief".to_string(),
            name: "Time Thief".to_string(),
            description: "Accumulate 10 hours of total focus time".to_string(),
            flavor_text: "10 hours stolen back from distraction.".to_string(),
            icon: "⌛".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalFocusTime { minutes: 600 },
            secret: false,
            share_text: "10 HOURS of focus! Stolen back from distractions. ⌛ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "TimeThief".to_string()],
        },
        BadgeDefinition {
            id: "time_lord".to_string(),
            name: "Time Lord".to_string(),
            description: "Accumulate 100 hours of total focus time".to_string(),
            flavor_text: "100 hours. You've mastered time itself.".to_string(),
            icon: "🕰️".to_string(),
            rarity: BadgeRarity::Epic,
            category: BadgeCategory::Milestone,
            criteria: BadgeCriteria::TotalFocusTime { minutes: 6000 },
            secret: false,
            share_text: "100 HOURS OF FOCUS. I am the Time Lord. 🕰️ #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "TimeLord".to_string()],
        },
        
        // ==================== SECRET BADGES ====================
        BadgeDefinition {
            id: "night_owl".to_string(),
            name: "Night Owl".to_string(),
            description: "Complete a session between midnight and 5am".to_string(),
            flavor_text: "The night belongs to the focused.".to_string(),
            icon: "🦉".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Secret,
            criteria: BadgeCriteria::Custom { key: "night_owl".to_string() },
            secret: true,
            share_text: "Late night focus session unlocked. 🦉 #DustoffReset #NightOwl".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "NightOwl".to_string()],
        },
        BadgeDefinition {
            id: "early_bird".to_string(),
            name: "Early Bird".to_string(),
            description: "Complete a session between 5am and 7am".to_string(),
            flavor_text: "You caught the worm.".to_string(),
            icon: "🐦".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Secret,
            criteria: BadgeCriteria::Custom { key: "early_bird".to_string() },
            secret: true,
            share_text: "Early morning focus session! 🐦 #DustoffReset #EarlyBird".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "EarlyBird".to_string()],
        },
        BadgeDefinition {
            id: "marathon".to_string(),
            name: "Marathon".to_string(),
            description: "Complete a 90+ minute session".to_string(),
            flavor_text: "An epic session. A feat of endurance.".to_string(),
            icon: "🏃".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Secret,
            criteria: BadgeCriteria::SessionDuration { minutes: 90 },
            secret: true,
            share_text: "90+ MINUTE SESSION. Marathon complete. 🏃 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Marathon".to_string()],
        },
        BadgeDefinition {
            id: "triple_threat".to_string(),
            name: "Triple Threat".to_string(),
            description: "Complete 3 sessions in a single day".to_string(),
            flavor_text: "Three sessions. One day. Absolute unit.".to_string(),
            icon: "🔱".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Secret,
            criteria: BadgeCriteria::SessionsInDay { count: 3 },
            secret: true,
            share_text: "3 SESSIONS IN ONE DAY! Triple threat! 🔱 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "TripleThreat".to_string()],
        },
        BadgeDefinition {
            id: "badge_collector".to_string(),
            name: "Badge Collector".to_string(),
            description: "Unlock 20 badges".to_string(),
            flavor_text: "Gotta catch 'em all.".to_string(),
            icon: "🎖️".to_string(),
            rarity: BadgeRarity::Rare,
            category: BadgeCategory::Secret,
            criteria: BadgeCriteria::BadgeCount { count: 20 },
            secret: true,
            share_text: "20 BADGES COLLECTED! 🎖️ #DustoffReset #BadgeCollector".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "BadgeCollector".to_string()],
        },
        
        // ==================== SOCIAL BADGES ====================
        BadgeDefinition {
            id: "first_share".to_string(),
            name: "Spread the Word".to_string(),
            description: "Share your first badge or session".to_string(),
            flavor_text: "You're helping others find focus.".to_string(),
            icon: "📢".to_string(),
            rarity: BadgeRarity::Common,
            category: BadgeCategory::Social,
            criteria: BadgeCriteria::ShareCount { count: 1 },
            secret: false,
            share_text: "Just shared my first Dustoff Reset achievement! 📢 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string()],
        },
        BadgeDefinition {
            id: "influencer".to_string(),
            name: "Influencer".to_string(),
            description: "Share 10 badges or sessions".to_string(),
            flavor_text: "You're building a focus movement.".to_string(),
            icon: "📣".to_string(),
            rarity: BadgeRarity::Uncommon,
            category: BadgeCategory::Social,
            criteria: BadgeCriteria::ShareCount { count: 10 },
            secret: false,
            share_text: "10 shares! Building the focus movement. 📣 #DustoffReset".to_string(),
            hashtags: vec!["DustoffReset".to_string(), "Influencer".to_string()],
        },
    ]
}

/// Get a badge definition by ID
pub fn get_badge_definition(badge_id: &str) -> Option<BadgeDefinition> {
    get_all_badge_definitions()
        .into_iter()
        .find(|b| b.id == badge_id)
}

/// Get all badges in a category
pub fn get_badges_by_category(category: BadgeCategory) -> Vec<BadgeDefinition> {
    get_all_badge_definitions()
        .into_iter()
        .filter(|b| b.category == category)
        .collect()
}

/// Get all non-secret badges (for display before unlock)
pub fn get_visible_badges() -> Vec<BadgeDefinition> {
    get_all_badge_definitions()
        .into_iter()
        .filter(|b| !b.secret)
        .collect()
}

/// Get badge count
pub fn get_total_badge_count() -> usize {
    get_all_badge_definitions().len()
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_badge_count() {
        let badges = get_all_badge_definitions();
        println!("Total badges defined: {}", badges.len());
        assert!(badges.len() >= 40, "Should have at least 40 badges");
    }
}
