import type { FloatingHUDProps } from "./types"

export const mockHUDProps: Record<string, Partial<FloatingHUDProps>> = {
  notCalibrated: {
    isCalibratedToday: false,
    bandwidthScore: null,
    mode: "not-calibrated",
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onStartSession: () => console.log("[v0] Start session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
  estimatedBandwidth: {
    isCalibratedToday: false,
    bandwidthScore: 62,
    estimatedDelta: 5,
    mode: "estimated",
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onStartSession: () => console.log("[v0] Start session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
  normalSession: {
    isCalibratedToday: true,
    bandwidthScore: 78,
    mode: "session",
    sessionMode: "Zen",
    sessionTime: 1500,
    timeRemaining: 1500,
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onStartSession: () => console.log("[v0] Start session"),
    onPauseSession: () => console.log("[v0] Pause session"),
    onStopSession: () => console.log("[v0] Stop session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
  flowSession: {
    isCalibratedToday: true,
    bandwidthScore: 85,
    mode: "session",
    sessionMode: "Flow",
    sessionTime: 900,
    timeRemaining: 2100,
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onStartSession: () => console.log("[v0] Start session"),
    onPauseSession: () => console.log("[v0] Pause session"),
    onStopSession: () => console.log("[v0] Stop session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
  legendSession: {
    isCalibratedToday: true,
    bandwidthScore: 92,
    mode: "session",
    sessionMode: "Legend",
    sessionTime: 1200,
    timeRemaining: 1800,
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onStartSession: () => console.log("[v0] Start session"),
    onPauseSession: () => console.log("[v0] Pause session"),
    onStopSession: () => console.log("[v0] Stop session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
  idle: {
    isCalibratedToday: true,
    bandwidthScore: 72,
    mode: "idle",
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onStartSession: () => console.log("[v0] Start session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
  paused: {
    isCalibratedToday: true,
    bandwidthScore: 68,
    mode: "paused",
    sessionMode: "Legend",
    sessionTime: 600,
    timeRemaining: 2400,
    onStartCalibration: () => console.log("[v0] Start calibration"),
    onResumeSession: () => console.log("[v0] Resume session"),
    onStopSession: () => console.log("[v0] Stop session"),
    onOpenParkingLot: () => console.log("[v0] Open parking lot"),
    onOpenHistory: () => console.log("[v0] Open history"),
    onOpenSettings: () => console.log("[v0] Open settings"),
  },
}
