// src/lib/badges/badge-definitions.ts

import { BadgeDefinition, BadgeCategory } from './types'

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ==================== MILESTONE BADGES ====================
  {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Complete your first focus session',
    flavorText: 'Every legend starts somewhere.',
    icon: '🩸',
    rarity: 'common',
    category: 'milestone',
    secret: false,
    shareText: 'Just completed my first focus session with Dustoff Reset! The journey begins. 🩸',
    hashtags: ['DustoffReset', 'FirstBlood', 'Focus'],
  },
  {
    id: 'getting_started',
    name: 'Getting Started',
    description: 'Complete 5 sessions',
    flavorText: "You're building a habit.",
    icon: '🌱',
    rarity: 'common',
    category: 'milestone',
    secret: false,
    shareText: '5 focus sessions down! Building the habit. 🌱',
    hashtags: ['DustoffReset', 'FocusHabit'],
  },
  {
    id: 'double_digits',
    name: 'Double Digits',
    description: 'Complete 10 sessions',
    flavorText: 'Consistency is showing.',
    icon: '🔟',
    rarity: 'uncommon',
    category: 'milestone',
    secret: false,
    shareText: '10 focus sessions complete! Double digits 🔟',
    hashtags: ['DustoffReset', 'Consistency'],
  },
  {
    id: 'quarter_century',
    name: 'Quarter Century',
    description: 'Complete 25 sessions',
    flavorText: "You're not messing around.",
    icon: '🎯',
    rarity: 'uncommon',
    category: 'milestone',
    secret: false,
    shareText: '25 focus sessions! This is becoming who I am. 🎯',
    hashtags: ['DustoffReset', 'FocusMode'],
  },
  {
    id: 'fifty_club',
    name: 'The Fifty Club',
    description: 'Complete 50 sessions',
    flavorText: 'Elite focus territory.',
    icon: '🏅',
    rarity: 'rare',
    category: 'milestone',
    secret: false,
    shareText: "50 sessions. I'm in the Fifty Club now. 🏅",
    hashtags: ['DustoffReset', 'FiftyClub'],
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Complete 100 sessions',
    flavorText: 'A hundred battles. A hundred victories.',
    icon: '💯',
    rarity: 'epic',
    category: 'milestone',
    secret: false,
    shareText: '100 FOCUS SESSIONS. I am the Centurion. 💯',
    hashtags: ['DustoffReset', 'Centurion', '100Sessions'],
  },

  // ==================== STREAK BADGES ====================
  {
    id: 'three_day_streak',
    name: 'Trilogy',
    description: '3-day focus streak',
    flavorText: 'Three days. A pattern emerges.',
    icon: '3️⃣',
    rarity: 'common',
    category: 'streak',
    secret: false,
    shareText: '3-day focus streak! The pattern is forming. 3️⃣',
    hashtags: ['DustoffReset', 'Streak'],
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: '7-day focus streak',
    flavorText: 'A full week of focus. Respect.',
    icon: '📅',
    rarity: 'uncommon',
    category: 'streak',
    secret: false,
    shareText: '7-DAY FOCUS STREAK! One full week. 📅',
    hashtags: ['DustoffReset', 'WeekWarrior', '7DayStreak'],
  },
  {
    id: 'fortnight_fighter',
    name: 'Fortnight Fighter',
    description: '14-day focus streak',
    flavorText: 'Two weeks of relentless focus.',
    icon: '⚔️',
    rarity: 'rare',
    category: 'streak',
    secret: false,
    shareText: '14-DAY STREAK! Two weeks of pure focus. ⚔️',
    hashtags: ['DustoffReset', '14DayStreak'],
  },
  {
    id: 'monthly_master',
    name: 'Monthly Master',
    description: '30-day focus streak',
    flavorText: "A month of mastery. You're different now.",
    icon: '🗓️',
    rarity: 'epic',
    category: 'streak',
    secret: false,
    shareText: "30-DAY FOCUS STREAK! A FULL MONTH! I'm not the same person I was. 🗓️",
    hashtags: ['DustoffReset', 'MonthlyMaster', '30DayStreak'],
  },
  {
    id: 'quarterly_quest',
    name: 'Quarterly Quest',
    description: '90-day focus streak',
    flavorText: 'Three months. This is your life now.',
    icon: '🏆',
    rarity: 'legendary',
    category: 'streak',
    secret: false,
    shareText: "90-DAY STREAK. THREE MONTHS. This isn't a phase—this is who I am. 🏆",
    hashtags: ['DustoffReset', '90DayStreak', 'Legendary'],
  },
  {
    id: 'yearly_legend',
    name: 'Yearly Legend',
    description: '365-day focus streak',
    flavorText: 'One year. Every. Single. Day. You are the legend.',
    icon: '👑',
    rarity: 'legendary',
    category: 'streak',
    secret: false,
    shareText: '365-DAY STREAK. ONE FULL YEAR. Every. Single. Day. 👑',
    hashtags: ['DustoffReset', 'YearlyLegend', '365Days'],
  },

  // ==================== PERFORMANCE BADGES ====================
  {
    id: 'flow_state',
    name: 'Flow State',
    description: 'Finish a session with bandwidth ≥ 80',
    flavorText: 'You found the zone.',
    icon: '⚡',
    rarity: 'uncommon',
    category: 'performance',
    secret: false,
    shareText: 'Achieved FLOW STATE! Finished with 80+ bandwidth. ⚡',
    hashtags: ['DustoffReset', 'FlowState'],
  },
  {
    id: 'untouchable',
    name: 'Untouchable',
    description: 'Finish a session with bandwidth ≥ 90',
    flavorText: 'Nothing could break your focus.',
    icon: '🛡️',
    rarity: 'rare',
    category: 'performance',
    secret: false,
    shareText: 'UNTOUCHABLE. 90+ bandwidth. Nothing broke my focus. 🛡️',
    hashtags: ['DustoffReset', 'Untouchable'],
  },
  {
    id: 'perfect_session',
    name: 'Perfect Session',
    description: 'Finish with 100 bandwidth (no penalties)',
    flavorText: 'Flawless. Absolutely flawless.',
    icon: '💎',
    rarity: 'epic',
    category: 'performance',
    secret: false,
    shareText: 'PERFECT SESSION. 100 bandwidth. Zero distractions. 💎',
    hashtags: ['DustoffReset', 'PerfectSession'],
  },
  {
    id: 'the_wall',
    name: 'The Wall',
    description: 'Complete a session with zero distractions',
    flavorText: 'They tried. They failed. The wall held.',
    icon: '🧱',
    rarity: 'rare',
    category: 'performance',
    secret: false,
    shareText: 'THE WALL HELD. Zero distractions. Nothing got through. 🧱',
    hashtags: ['DustoffReset', 'TheWall'],
  },
  {
    id: 'laser_focus',
    name: 'Laser Focus',
    description: 'Return from every delay gate in a session',
    flavorText: 'Tempted every time. Resisted every time.',
    icon: '🎯',
    rarity: 'rare',
    category: 'performance',
    secret: false,
    shareText: 'LASER FOCUS. Returned from every temptation. 🎯',
    hashtags: ['DustoffReset', 'LaserFocus'],
  },

  // ==================== MODE BADGES ====================
  {
    id: 'zen_initiate',
    name: 'Zen Initiate',
    description: 'Complete 5 Zen mode sessions',
    flavorText: 'The training grounds welcome you.',
    icon: '🧘',
    rarity: 'common',
    category: 'mode',
    secret: false,
    shareText: 'Zen Initiate. 5 sessions in the training grounds. 🧘',
    hashtags: ['DustoffReset', 'ZenMode'],
  },
  {
    id: 'flow_rider',
    name: 'Flow Rider',
    description: 'Complete 10 Flow mode sessions',
    flavorText: 'You ride the wave of focus.',
    icon: '🌊',
    rarity: 'uncommon',
    category: 'mode',
    secret: false,
    shareText: 'Flow Rider! 10 sessions riding the focus wave. 🌊',
    hashtags: ['DustoffReset', 'FlowMode'],
  },
  {
    id: 'legend_born',
    name: 'Legend Born',
    description: 'Complete your first Legend mode session',
    flavorText: 'You stepped into the arena.',
    icon: '⚔️',
    rarity: 'uncommon',
    category: 'mode',
    secret: false,
    shareText: 'LEGEND BORN. I stepped into the arena. ⚔️',
    hashtags: ['DustoffReset', 'LegendMode', 'LegendBorn'],
  },
  {
    id: 'legend_proven',
    name: 'Legend Proven',
    description: 'Complete 10 Legend mode sessions',
    flavorText: 'The arena knows your name.',
    icon: '🔥',
    rarity: 'rare',
    category: 'mode',
    secret: false,
    shareText: 'LEGEND PROVEN. 10 sessions in the arena. 🔥',
    hashtags: ['DustoffReset', 'LegendProven'],
  },
  {
    id: 'legend_eternal',
    name: 'Legend Eternal',
    description: 'Complete 50 Legend mode sessions',
    flavorText: 'Your legend will echo through eternity.',
    icon: '👑',
    rarity: 'legendary',
    category: 'mode',
    secret: false,
    shareText: 'LEGEND ETERNAL. 50 sessions in the arena. My legend echoes forever. 👑',
    hashtags: ['DustoffReset', 'LegendEternal'],
  },
  {
    id: 'extension_survivor',
    name: 'Extension Survivor',
    description: 'Survive a +5 minute session extension in Legend mode',
    flavorText: 'They extended your suffering. You endured.',
    icon: '⏱️',
    rarity: 'rare',
    category: 'mode',
    secret: false,
    shareText: 'Session extended +5 min. I SURVIVED. ⏱️',
    hashtags: ['DustoffReset', 'ExtensionSurvivor'],
  },
  {
    id: 'triple_extension',
    name: 'Triple Extension',
    description: 'Survive 3+ extensions in a single Legend session',
    flavorText: "15 extra minutes of hell. You're still here.",
    icon: '💀',
    rarity: 'epic',
    category: 'mode',
    secret: false,
    shareText: '3 EXTENSIONS. +15 MINUTES. I SURVIVED THE GAUNTLET. 💀',
    hashtags: ['DustoffReset', 'TripleExtension'],
  },

  // ==================== SHAME BADGES ====================
  {
    id: 'the_fall',
    name: 'The Fall',
    description: 'Finish a session with bandwidth ≤ 20',
    flavorText: "You fell. But you didn't quit.",
    icon: '📉',
    rarity: 'shame',
    category: 'shame',
    secret: false,
    shareText: "I fell hard today. Bandwidth: 📉 But I didn't quit.",
    hashtags: ['DustoffReset', 'WalkOfShame'],
  },
  {
    id: 'rock_bottom',
    name: 'Rock Bottom',
    description: 'Finish a session with bandwidth ≤ 5',
    flavorText: 'You hit the floor. The only way is up.',
    icon: '🪨',
    rarity: 'shame',
    category: 'shame',
    secret: false,
    shareText: 'ROCK BOTTOM. Bandwidth nearly zero. But I finished. 🪨',
    hashtags: ['DustoffReset', 'RockBottom', 'WalkOfShame'],
  },
  {
    id: 'one_hp',
    name: 'One HP',
    description: 'Finish a session with exactly 1 bandwidth',
    flavorText: 'Hanging by a thread. Still alive.',
    icon: '💔',
    rarity: 'shame',
    category: 'shame',
    secret: true,
    shareText: 'Finished with EXACTLY 1 BANDWIDTH. One HP left. Still standing. 💔',
    hashtags: ['DustoffReset', 'OneHP'],
  },
  {
    id: 'doomscroller',
    name: 'Doomscroller',
    description: 'Get blocked 5+ times in a single session',
    flavorText: 'The wall had to work overtime.',
    icon: '📱',
    rarity: 'shame',
    category: 'shame',
    secret: false,
    shareText: 'I tried to escape 5+ times today. The wall said no. 📱',
    hashtags: ['DustoffReset', 'Doomscroller'],
  },
  {
    id: 'serial_offender',
    name: 'Serial Offender',
    description: 'Get blocked 10+ times in a single session',
    flavorText: 'You really tried everything, huh?',
    icon: '🚨',
    rarity: 'shame',
    category: 'shame',
    secret: false,
    shareText: "10+ BLOCKS in one session. I'm a serial offender. 🚨",
    hashtags: ['DustoffReset', 'SerialOffender'],
  },
  {
    id: 'no_willpower',
    name: 'No Willpower',
    description: 'Wait through every delay gate without returning',
    flavorText: 'You watched every countdown. Chose distraction every time.',
    icon: '🫠',
    rarity: 'shame',
    category: 'shame',
    secret: false,
    shareText: 'Zero willpower today. Waited through every gate. 🫠',
    hashtags: ['DustoffReset', 'NoWillpower'],
  },

  // ==================== RESILIENCE BADGES ====================
  {
    id: 'redemption_arc',
    name: 'Redemption Arc',
    description: 'Get a Flow State badge after getting The Fall',
    flavorText: 'You fell. You rose. You conquered.',
    icon: '🔄',
    rarity: 'rare',
    category: 'resilience',
    secret: true,
    shareText: 'THE REDEMPTION ARC IS COMPLETE. I fell. I rose. I conquered. 🔄',
    hashtags: ['DustoffReset', 'RedemptionArc'],
  },
  {
    id: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Complete a session after breaking a streak',
    flavorText: "The streak died. You didn't.",
    icon: '🔙',
    rarity: 'uncommon',
    category: 'resilience',
    secret: false,
    shareText: 'Broke my streak. Came back anyway. 🔙',
    hashtags: ['DustoffReset', 'ComebackKid'],
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    description: 'Rebuild a 7+ day streak after losing one',
    flavorText: 'From the ashes, you rise.',
    icon: '🐦‍🔥',
    rarity: 'epic',
    category: 'resilience',
    secret: true,
    shareText: 'Lost my streak. Built a new one. PHOENIX RISING. 🐦‍🔥',
    hashtags: ['DustoffReset', 'Phoenix'],
  },

  // ==================== TIME BADGES ====================
  {
    id: 'hour_hero',
    name: 'Hour Hero',
    description: 'Accumulate 1 hour of total focus time',
    flavorText: 'Your first hour of reclaimed time.',
    icon: '⏰',
    rarity: 'common',
    category: 'milestone',
    secret: false,
    shareText: '1 HOUR of focus time with Dustoff Reset! ⏰',
    hashtags: ['DustoffReset', 'FocusTime'],
  },
  {
    id: 'time_thief',
    name: 'Time Thief',
    description: 'Accumulate 10 hours of total focus time',
    flavorText: '10 hours stolen back from distraction.',
    icon: '⌛',
    rarity: 'uncommon',
    category: 'milestone',
    secret: false,
    shareText: '10 HOURS of focus! Stolen back from distractions. ⌛',
    hashtags: ['DustoffReset', 'TimeThief'],
  },
  {
    id: 'time_lord',
    name: 'Time Lord',
    description: 'Accumulate 100 hours of total focus time',
    flavorText: "100 hours. You've mastered time itself.",
    icon: '🕰️',
    rarity: 'epic',
    category: 'milestone',
    secret: false,
    shareText: '100 HOURS OF FOCUS. I am the Time Lord. 🕰️',
    hashtags: ['DustoffReset', 'TimeLord'],
  },

  // ==================== SECRET BADGES ====================
  {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Complete a session between midnight and 5am',
    flavorText: 'The night belongs to the focused.',
    icon: '🦉',
    rarity: 'uncommon',
    category: 'secret',
    secret: true,
    shareText: 'Late night focus session unlocked. 🦉',
    hashtags: ['DustoffReset', 'NightOwl'],
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Complete a session between 5am and 7am',
    flavorText: 'You caught the worm.',
    icon: '🐦',
    rarity: 'uncommon',
    category: 'secret',
    secret: true,
    shareText: 'Early morning focus session! 🐦',
    hashtags: ['DustoffReset', 'EarlyBird'],
  },
  {
    id: 'marathon',
    name: 'Marathon',
    description: 'Complete a 90+ minute session',
    flavorText: 'An epic session. A feat of endurance.',
    icon: '🏃',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    shareText: '90+ MINUTE SESSION. Marathon complete. 🏃',
    hashtags: ['DustoffReset', 'Marathon'],
  },
  {
    id: 'triple_threat',
    name: 'Triple Threat',
    description: 'Complete 3 sessions in a single day',
    flavorText: 'Three sessions. One day. Absolute unit.',
    icon: '🔱',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    shareText: '3 SESSIONS IN ONE DAY! Triple threat! 🔱',
    hashtags: ['DustoffReset', 'TripleThreat'],
  },
  {
    id: 'badge_collector',
    name: 'Badge Collector',
    description: 'Unlock 20 badges',
    flavorText: "Gotta catch 'em all.",
    icon: '🎖️',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    shareText: '20 BADGES COLLECTED! 🎖️',
    hashtags: ['DustoffReset', 'BadgeCollector'],
  },

  // ==================== SOCIAL BADGES ====================
  {
    id: 'first_share',
    name: 'Spread the Word',
    description: 'Share your first badge or session',
    flavorText: "You're helping others find focus.",
    icon: '📢',
    rarity: 'common',
    category: 'social',
    secret: false,
    shareText: 'Just shared my first Dustoff Reset achievement! 📢',
    hashtags: ['DustoffReset'],
  },
  {
    id: 'influencer',
    name: 'Influencer',
    description: 'Share 10 badges or sessions',
    flavorText: "You're building a focus movement.",
    icon: '📣',
    rarity: 'uncommon',
    category: 'social',
    secret: false,
    shareText: '10 shares! Building the focus movement. 📣',
    hashtags: ['DustoffReset', 'Influencer'],
  },
]

// Helper functions
export function getBadgeById(id: string): BadgeDefinition | undefined {
  return BADGE_DEFINITIONS.find(b => b.id === id)
}

export function getBadgesByCategory(category: BadgeCategory): BadgeDefinition[] {
  return BADGE_DEFINITIONS.filter(b => b.category === category)
}

export function getVisibleBadges(): BadgeDefinition[] {
  return BADGE_DEFINITIONS.filter(b => !b.secret)
}

export function getSecretBadges(): BadgeDefinition[] {
  return BADGE_DEFINITIONS.filter(b => b.secret)
}

export function getTotalBadgeCount(): number {
  return BADGE_DEFINITIONS.length
}
